export const performanceData = [
  { date: "Jan", value: 10000 },
  { date: "Fév", value: 10800 },
  { date: "Mar", value: 10400 },
  { date: "Avr", value: 11200 },
  { date: "Mai", value: 11900 },
  { date: "Jun", value: 11600 },
  { date: "Jul", value: 12800 },
  { date: "Aoû", value: 12200 },
  { date: "Sep", value: 13100 },
  { date: "Oct", value: 13800 },
  { date: "Nov", value: 13200 },
  { date: "Déc", value: 14450 },
];

export const recentPositions = [
  { id: 1, asset: "BTC/USD", direction: "LONG", entry: 42350, current: 44120, pnl: +1770, pnlPct: +4.18 },
  { id: 2, asset: "ETH/USD", direction: "SHORT", entry: 2890, current: 2740, pnl: +150, pnlPct: +5.19 },
  { id: 3, asset: "EUR/USD", direction: "LONG", entry: 1.0821, current: 1.0798, pnl: -23, pnlPct: -0.21 },
  { id: 4, asset: "AAPL", direction: "LONG", entry: 178.5, current: 183.2, pnl: +470, pnlPct: +2.63 },
  { id: 5, asset: "GOLD", direction: "LONG", entry: 1985, current: 2018, pnl: +330, pnlPct: +1.66 },
];

export const signals = [
  { id: 1, asset: "BTC/USD", signal: "BUY", confidence: 92, timeframe: "4H", price: 44120 },
  { id: 2, asset: "SOL/USD", signal: "BUY", confidence: 87, timeframe: "1D", price: 98.4 },
  { id: 3, asset: "EUR/USD", signal: "HOLD", confidence: 61, timeframe: "1H", price: 1.0798 },
  { id: 4, asset: "AAPL", signal: "BUY", confidence: 78, timeframe: "1D", price: 183.2 },
  { id: 5, asset: "US30", signal: "SELL", confidence: 73, timeframe: "4H", price: 38420 },
  { id: 6, asset: "GOLD", signal: "HOLD", confidence: 55, timeframe: "1W", price: 2018 },
];

export const marketNews = [
  { id: 1, title: "La Fed maintient ses taux directeurs stables pour le 3e mois consécutif", source: "Reuters", time: "Il y a 12 min", impact: "HIGH", category: "Macro" },
  { id: 2, title: "Bitcoin franchit la résistance clé des 44 000 $ — Analyse technique", source: "CoinDesk", time: "Il y a 34 min", impact: "MEDIUM", category: "Crypto" },
  { id: 3, title: "Apple dépasse les attentes au Q4 avec un BPA de 2,18 $", source: "Bloomberg", time: "Il y a 1h", impact: "HIGH", category: "Actions" },
  { id: 4, title: "L'or teste un nouveau sommet à 2 020 $ dans un contexte d'incertitude", source: "FT", time: "Il y a 2h", impact: "MEDIUM", category: "Commodities" },
  { id: 5, title: "L'EUR/USD sous pression après les données d'inflation européennes", source: "FX Street", time: "Il y a 3h", impact: "LOW", category: "Forex" },
];

export const strategies = [
  {
    id: 1,
    name: "RSI Reversal Pro",
    style: "Swing Trading",
    description: "Identifie les zones de sur-achat et sur-vente avec le RSI pour capturer les retournements de tendance à moyen terme.",
    winRate: 71.4,
    maxDrawdown: 8.2,
    tradesBacktested: 1240,
    riskLevel: "Medium",
    timeframes: ["4H", "1D"],
    markets: ["Forex", "Indices", "Crypto"],
    entryConditions: ["RSI < 30 (survente) ou RSI > 70 (surachat)", "Divergence haussière/baissière confirmée", "Volume supérieur à la moyenne 20 périodes"],
    exitConditions: ["RSI atteint la zone neutre (45-55)", "Signal adverse du MACD", "Trailing stop à 1.5 ATR"],
    equityCurve: [10000, 10420, 10180, 10850, 11200, 10980, 11650, 12100, 11800, 12450],
    pros: ["Taux de réussite élevé", "Faible drawdown", "Applicable sur plusieurs marchés"],
    cons: ["Signaux rares en marché tendanciel", "Nécessite de la patience"],
    recommendedAssets: ["EUR/USD", "GBP/USD", "BTC/USD", "S&P 500"],
  },
  {
    id: 2,
    name: "EMA Crossover Elite",
    style: "Day Trading",
    description: "Exploite le croisement des moyennes mobiles exponentielles 9 et 21 pour suivre les tendances intraday.",
    winRate: 64.8,
    maxDrawdown: 12.5,
    tradesBacktested: 3820,
    riskLevel: "Medium",
    timeframes: ["15M", "1H"],
    markets: ["Forex", "Crypto"],
    entryConditions: ["Croisement EMA 9 au-dessus de l'EMA 21 (achat)", "Prix au-dessus des deux EMAs", "RSI entre 50 et 70"],
    exitConditions: ["Croisement inverse des EMAs", "Prix clôture sous l'EMA 21", "Objectif de profit à 2R"],
    equityCurve: [10000, 10200, 9900, 10600, 10400, 11100, 11400, 11200, 12000, 12800],
    pros: ["Nombreux signaux", "Facile à automatiser", "Bon suivi de tendance"],
    cons: ["Whipsaws en range", "Drawdown modéré"],
    recommendedAssets: ["EUR/USD", "GBP/JPY", "BTC/USD", "ETH/USD"],
  },
  {
    id: 3,
    name: "Breakout Momentum",
    style: "Day Trading",
    description: "Capture les ruptures de niveaux clés avec confirmation de volume pour des mouvements directionnels puissants.",
    winRate: 58.2,
    maxDrawdown: 15.8,
    tradesBacktested: 2150,
    riskLevel: "High",
    timeframes: ["1H", "4H"],
    markets: ["Crypto", "Indices", "Actions"],
    entryConditions: ["Rupture confirmée d'un niveau S/R majeur", "Volume x2 par rapport à la moyenne", "Bougie de clôture au-delà du niveau"],
    exitConditions: ["Objectif basé sur la hauteur du range", "Stop-loss sous le niveau cassé", "Trailing stop à 2 ATR"],
    equityCurve: [10000, 11200, 10600, 11800, 12500, 11900, 13200, 14100, 13600, 15200],
    pros: ["Ratio R/R excellent", "Mouvements puissants", "Clair à identifier"],
    cons: ["Faux breakouts fréquents", "Drawdown plus élevé"],
    recommendedAssets: ["BTC/USD", "ETH/USD", "NASDAQ", "US30"],
  },
  {
    id: 4,
    name: "Smart Money Concepts",
    style: "Swing Trading",
    description: "Suit les flux institutionnels en identifiant les order blocks, fair value gaps et liquidity sweeps.",
    winRate: 68.9,
    maxDrawdown: 9.4,
    tradesBacktested: 890,
    riskLevel: "Medium",
    timeframes: ["4H", "1D", "1W"],
    markets: ["Forex", "Indices", "Crypto"],
    entryConditions: ["Liquidity sweep confirmé", "Retour sur un order block institutionnel", "Structure de marché haussière/baissière"],
    exitConditions: ["Atteinte du prochain niveau de liquidité", "Changement de structure (CHoCH)", "Objectif de 3R minimum"],
    equityCurve: [10000, 10350, 10180, 10720, 11100, 11400, 11200, 11850, 12300, 13100],
    pros: ["Vision institutionnelle", "Très faible drawdown", "Haute précision d'entrée"],
    cons: ["Courbe d'apprentissage importante", "Signaux rares"],
    recommendedAssets: ["EUR/USD", "GBP/USD", "XAU/USD", "BTC/USD"],
  },
  {
    id: 5,
    name: "Mean Reversion Alpha",
    style: "Scalping",
    description: "Exploite le retour à la moyenne statistique sur des timeframes courts avec des bandes de Bollinger.",
    winRate: 74.1,
    maxDrawdown: 6.8,
    tradesBacktested: 5640,
    riskLevel: "Low",
    timeframes: ["1M", "5M", "15M"],
    markets: ["Forex", "Indices"],
    entryConditions: ["Prix en dehors des bandes de Bollinger (2σ)", "RSI en zone extrême", "Volume faible (pas de breakout)"],
    exitConditions: ["Retour à la moyenne (EMA 20)", "Stop-loss serré à 0.5 ATR", "Objectif à 1R minimum"],
    equityCurve: [10000, 10150, 10280, 10420, 10380, 10590, 10720, 10880, 11020, 11180],
    pros: ["Très haut taux de réussite", "Drawdown minimal", "Nombreux trades"],
    cons: ["Profits unitaires faibles", "Nécessite une exécution rapide"],
    recommendedAssets: ["EUR/USD", "USD/JPY", "DAX", "S&P 500"],
  },
  {
    id: 6,
    name: "MACD Trend Following",
    style: "Position Trading",
    description: "Stratégie de suivi de tendance longue durée basée sur le MACD et les niveaux de structure majeurs.",
    winRate: 61.5,
    maxDrawdown: 18.2,
    tradesBacktested: 480,
    riskLevel: "Low",
    timeframes: ["1D", "1W"],
    markets: ["Actions", "Commodities", "Indices"],
    entryConditions: ["Croisement MACD haussier/baissier confirmé", "Histogramme en expansion", "Prix au-dessus/dessous des SMA 50 et 200"],
    exitConditions: ["Croisement MACD adverse", "Signal de retournement mensuel", "Trailing stop à 5% du capital"],
    equityCurve: [10000, 10800, 11600, 12500, 11800, 13200, 14100, 13600, 15200, 16800],
    pros: ["Profits très importants", "Peu de trades", "Faible stress"],
    cons: ["Nécessite beaucoup de patience", "Drawdowns importants temporaires"],
    recommendedAssets: ["AAPL", "MSFT", "GOLD", "S&P 500"],
  },
];

export const economicEvents = [
  { id: 1, date: "2024-01-15", time: "14:30", country: "🇺🇸", event: "CPI (Inflation) m/m", impact: "HIGH", previous: "0.1%", forecast: "0.2%", actual: "0.3%" },
  { id: 2, date: "2024-01-15", time: "14:30", country: "🇺🇸", event: "Core CPI m/m", impact: "HIGH", previous: "0.3%", forecast: "0.3%", actual: "0.3%" },
  { id: 3, date: "2024-01-16", time: "13:30", country: "🇺🇸", event: "Retail Sales m/m", impact: "MEDIUM", previous: "0.3%", forecast: "0.2%", actual: null },
  { id: 4, date: "2024-01-17", time: "09:00", country: "🇪🇺", event: "BCE — Discours de Lagarde", impact: "HIGH", previous: "-", forecast: "-", actual: null },
  { id: 5, date: "2024-01-19", time: "13:30", country: "🇺🇸", event: "NFP — Non-Farm Payrolls", impact: "HIGH", previous: "199K", forecast: "187K", actual: null },
  { id: 6, date: "2024-01-22", time: "15:00", country: "🇺🇸", event: "FED — Décision taux directeurs", impact: "HIGH", previous: "5.50%", forecast: "5.50%", actual: null },
  { id: 7, date: "2024-01-23", time: "09:30", country: "🇬🇧", event: "UK CPI y/y", impact: "MEDIUM", previous: "3.9%", forecast: "3.8%", actual: null },
  { id: 8, date: "2024-01-24", time: "10:00", country: "🇪🇺", event: "PMI Manufacturier", impact: "MEDIUM", previous: "44.4", forecast: "44.8", actual: null },
  { id: 9, date: "2024-01-25", time: "13:30", country: "🇨🇦", event: "GDP m/m", impact: "MEDIUM", previous: "0.0%", forecast: "0.1%", actual: null },
  { id: 10, date: "2024-01-26", time: "13:30", country: "🇺🇸", event: "PCE Price Index m/m", impact: "HIGH", previous: "0.1%", forecast: "0.2%", actual: null },
];

export const journalEntries = [
  { id: 1, date: "2024-01-14", asset: "BTC/USD", direction: "LONG", result: "WIN", pnl: +1250, comment: "Breakout de la résistance 42K avec volume fort" },
  { id: 2, date: "2024-01-13", asset: "EUR/USD", direction: "SHORT", result: "LOSS", pnl: -320, comment: "Stop touché avant le mouvement attendu" },
  { id: 3, date: "2024-01-12", asset: "AAPL", direction: "LONG", result: "WIN", pnl: +680, comment: "Rebond sur support hebdomadaire, conf. RSI" },
  { id: 4, date: "2024-01-11", asset: "GOLD", direction: "LONG", result: "WIN", pnl: +890, comment: "Contexte macro favorable, FED dovish" },
  { id: 5, date: "2024-01-10", asset: "SOL/USD", direction: "LONG", result: "WIN", pnl: +2100, comment: "EMA crossover 4H avec fort momentum" },
  { id: 6, date: "2024-01-09", asset: "US30", direction: "SHORT", result: "LOSS", pnl: -450, comment: "Mauvais timing, résistance pas encore atteinte" },
  { id: 7, date: "2024-01-08", asset: "ETH/USD", direction: "LONG", result: "WIN", pnl: +1540, comment: "Smart money order block, confluence parfaite" },
  { id: 8, date: "2024-01-05", asset: "GBP/USD", direction: "SHORT", result: "WIN", pnl: +380, comment: "Retournement sous résistance majeure" },
];
